export const PERSON_TYPE = 'PERSON';
export const FLEET_TYPE = 'FLEET';

export const DOCUMENT_STATUS_PENDING = 'PENDING';
export const DOCUMENT_STATUS_APPROVED = 'APPROVED';
export const DOCUMENT_STATUS_REJECTED = 'REJECTED';

export const PERSON_STATUS_ACTIVE = 'ACTIVE';

export const FEEDBACK_STATUS_PENDING = 'PENDING';
export const FEEDBACK_STATUS_APPROVED = 'APPROVED';
